### ISSUE TITLE
RP和BP問題

### ISSUE THREAD

**Issue by yjo4nk45m3** [frank89722/SmileLawnComplexPack#3]
ID：6461&6048衝突 導致RP無法使用
BP timer 無法開關，無法調時距

**Comment by frank89722** [comment]
我會再1.0.1修復

**Comment by yjo4nk45m3** [comment]
更新錯誤內容：
BP的GUI大概是全掛了?
像counter,timer,等RP需GUI者皆為永遠的2秒
其餘bug有待他人測試

**Comment by frank89722** [comment]
請不要使用物品id請直接給我物品名稱

**Comment by yjo4nk45m3** [comment]
BP : Stone Tile (6048)
RP : Circuit Plate (6461)

**Comment by frank89722** [comment]
已經在1.0.1修正了,待上傳
