### ISSUE TITLE
伺服崩潰

### ISSUE THREAD

**Issue by SoanEx** [frank89722/SmileLawnComplexPack#4]
slcp 3.0
ID 551 Crystal Growth Chamber
放置會導致伺服崩潰

**Comment by frank89722** [comment]
Crash Report?

**Comment by SoanEx** [comment]
我不是服主耶...不一定拿的到
還有AE 的controller 合成是使用半磚方塊是正常嗎

**Comment by frank89722** [comment]
請至slcp2github回報錯誤
